# Force Ubuntu 16.04 "Xenial" to get newer GCC, binutils etc.
dist: xenial

language: julia
sudo: false
os:
  - linux
  - osx
julia:
  - 1.0
  - 1.1
  - 1.2
  - nightly
matrix:
  allow_failures:
    - julia: nightly
    - os: osx
addons:
    apt:
        packages:
           - cmake
           - cmake-data
           - gfortran
           - libblas-dev
           - liblapack-dev
           - libgmp-dev
           - libmpfr-dev

notifications:
  - email: false
script:
  - while sleep 30; do echo "still alive"; done &
  - julia -e 'using Pkg; Pkg.add([PackageSpec(url="https://github.com/oscar-system/Singular.jl.git"),PackageSpec(url="https://github.com/a-kulkarn/Dory.git")]);'
  - julia -e 'using Pkg; Pkg.build("Singular");'
env:
   global:
      - DOCUMENTER_DEBUG=true

jobs:
  include:
    - stage: "Documentation"
      julia: 1.0
      os: linux
      script:
        - while sleep 30; do echo "still alive"; done &
        - julia --project=docs/ -e 'using Pkg; Pkg.add([PackageSpec(url="https://github.com/oscar-system/Singular.jl.git"),PackageSpec(url="https://github.com/a-kulkarn/Dory.git")]);'
        - julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate()'
        - julia --project=docs/ docs/make.jl
      after_success: skip
